version: '3.4'

services:
  shopping:
    image: threax.shopping
    container_name: shopping
    build:
      context: .
      dockerfile: Shopping/Dockerfile
    networks:
      - appnet
    volumes:
      - type: bind
        source: ../TrustedRoots
        target: /usr/local/share/ca-certificates
      - type: bind
        source: ../DevData/shopping
        target: /appdata
    labels:
      - "threax.nginx.host=shopping.dev.threax.com"

networks:
  appnet:
    external: true